a=int(input("Enter the first number: "))
b=int(input("Enter the second number: "))
print(a+b)
print(a-b)
print(a*b)
print(a/b)
x=input("Enter the first name: ")
y=input("Enter the last name: ")
print(x+y)
print("Hello,Vivek Raj Verma! welcome to the python program")